### ISSUE TITLE
Change the sniff pattern

### ISSUE THREAD

**Issue by baires** [nanobox-io/nanobox-engine-wordpress#3]
In some cases, we dont have a full WP installation pushed to our repositories, because we dont want the WP core there.

The sniff is especting to find a `wp-login.php` and like I said before it will fail because that file is not on the repo. But if we change the pattern to look for `wp-content/` it should be fine.

Thoughts?

**Comment by sanderson** [comment]
@Baires Great thought. Makes total sense and isn't a major change. @notxarb is the main author of the engine. I'll have him look at the change.

**Comment by baires** [comment]
:+1:

**Comment by sanderson** [comment]
@Baires Your suggestion has been implemented into the most recent version of the Engine. We still have to update the distributed build images in order sniff script to work, but you can specify the `wordpress` engine in your [Boxfile](https://docs.nanobox.io/boxfile/build/).

``` yaml
build:
  engine: wordpress
```

Once the build images are updated, I'll close this issue.

**Comment by baires** [comment]
Awesome!
